# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('server', '0001_initial'),
        ('instance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddIns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vm_name', models.CharField(max_length=30, verbose_name='\u865a\u62df\u673a\u540d\u79f0')),
                ('cpu_num', models.IntegerField(default=0, verbose_name='CPU(\u6838)')),
                ('cpu_model', models.IntegerField(default=1, help_text='\u6b64\u529f\u80fd\u6682\u65f6\u672a\u5b9e\u73b0\uff08\u914d\u65b9\uff09\uff0c\u5168\u90e8\u9ed8\u8ba4\u4e3a1', verbose_name='CPU\u6a21\u5f0f')),
                ('disk_model', models.IntegerField(default=1, help_text='\u6b64\u529f\u80fd\u6682\u65f6\u672a\u5b9e\u73b0\uff08\u914d\u65b9\uff09\uff0c\u5168\u90e8\u9ed8\u8ba4\u4e3a1', verbose_name='\u6570\u636e\u76d8\u6a21\u5f0f')),
                ('sys_disk_size', models.BigIntegerField(default=0, help_text='\u5355\u4f4d: Byte', verbose_name='\u7cfb\u7edf\u76d8\u5927\u5c0f')),
                ('data_disk_size', models.BigIntegerField(default=0, help_text='\u5355\u4f4d: Byte', verbose_name='\u6570\u636e\u76d8\u76d8\u5927\u5c0f')),
                ('mem_size', models.BigIntegerField(default=0, help_text='\u5355\u4f4d: Byte', verbose_name='\u5185\u5b58\u5927\u5c0f')),
            ],
            options={
                'verbose_name': '\u521b\u5efa\u865a\u62df\u673a',
                'verbose_name_plural': '3-\u521b\u5efa\u865a\u62df\u673a',
            },
        ),
        migrations.CreateModel(
            name='AddVmFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(default='', max_length=1000, verbose_name='\u4e0b\u8f7d\u5730\u5740')),
                ('size', models.IntegerField(default=0, verbose_name='\u6587\u4ef6\u5927\u5c0f')),
                ('md5', models.CharField(default='', max_length=45, verbose_name='MD5')),
                ('save_path', models.CharField(default='', max_length=45, verbose_name='\u4fdd\u5b58\u8def\u5f84')),
                ('format', models.IntegerField(default=0, help_text='0-iso, 1-qcow2, 3-\u672a\u77e5 ', verbose_name='\u6587\u4ef6\u7c7b\u578b')),
            ],
            options={
                'verbose_name': '\u6dfb\u52a0\u955c\u50cf\u6587\u4ef6',
                'verbose_name_plural': '8-\u6dfb\u52a0\u955c\u50cf\u6587\u4ef6',
            },
        ),
        migrations.CreateModel(
            name='CtrlIns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=10, verbose_name='\u64cd\u4f5c')),
            ],
            options={
                'verbose_name': '\u865a\u62df\u673a\u5f00\u5173\u673a',
                'verbose_name_plural': '7-\u865a\u62df\u673a\u5f00\u5173\u673a',
            },
        ),
        migrations.CreateModel(
            name='DelIns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('del_disk', models.IntegerField(default=0, help_text='0-\u5220\u9664, 1-\u4e0d\u5220\u9664', verbose_name='\u5220\u9664\u6570\u636e\u76d8')),
            ],
            options={
                'verbose_name': '\u5220\u9664\u865a\u62df\u673a',
                'verbose_name_plural': '4-\u5220\u9664\u865a\u62df\u673a',
            },
        ),
        migrations.CreateModel(
            name='SetNetIns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nic_name', models.CharField(max_length=45, verbose_name='\u7f51\u5361\u540d\u79f0')),
                ('ip', models.CharField(default='', max_length=45, verbose_name='\u7ed1\u5b9aIP')),
                ('bootproto', models.CharField(default='', max_length=45, verbose_name='\u7c7b\u578b')),
                ('netmask', models.CharField(default='', max_length=45, verbose_name='\u5b50\u7f51\u63a9\u7801')),
                ('gateway', models.CharField(default='', max_length=45, verbose_name='\u7f51\u5173')),
                ('dns', models.CharField(default='', max_length=45, verbose_name='DNS')),
            ],
            options={
                'verbose_name': '\u914d\u7f6e\u7f51\u5361',
                'verbose_name_plural': '9-\u914d\u7f6e\u7f51\u5361',
            },
        ),
        migrations.CreateModel(
            name='SettingIns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_cpu_num', models.IntegerField(verbose_name='\u65b0CPU\u914d\u7f6e(\u6838)')),
                ('sysdisk_extend', models.BigIntegerField(default=0, help_text='\u5355\u4f4d: Byte', verbose_name='\u65b0\u589e\u7cfb\u7edf\u76d8\u5927\u5c0f')),
                ('datadisk_extend', models.BigIntegerField(default=0, help_text='\u5355\u4f4d: Byte', verbose_name='\u65b0\u589e\u6570\u636e\u76d8\u76d8\u5927\u5c0f')),
                ('new_mem_size', models.BigIntegerField(default=0, help_text='\u5355\u4f4d: Byte', verbose_name='\u65b0\u5185\u5b58\u5927\u5c0f')),
            ],
            options={
                'verbose_name': '\u865a\u62df\u673a\u589e\u52a0\u914d\u7f6e',
                'verbose_name_plural': '6-\u865a\u62df\u673a\u589e\u52a0\u914d\u7f6e',
            },
        ),
        migrations.CreateModel(
            name='SnapIns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snap_name', models.CharField(max_length=50, verbose_name='\u5feb\u7167\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u5feb\u7167\u76f8\u5173\u64cd\u4f5c',
                'verbose_name_plural': '5-\u5feb\u7167\u76f8\u5173\u64cd\u4f5c',
            },
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('create_time', models.CharField(default='2016-01-01 00:00:00', help_text='\u521b\u5efa\u65f6\u63d2\u5165\u5f53\u524d\u65f6\u95f4', max_length=20, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('end_time', models.CharField(default='2016-01-01 00:00:00', help_text='\u521b\u5efa\u65f6\u63d2\u5165\u5f53\u524d\u65f6\u95f4', max_length=20, verbose_name='\u5b8c\u6210\u65f6\u95f4')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('group_id', models.CharField(default=None, max_length=32, null=True, verbose_name='\u4efb\u52a1\u7ec4ID')),
                ('father_id', models.CharField(default=None, max_length=32, null=True, verbose_name='\u7236\u4efb\u52a1ID')),
                ('status', models.IntegerField(default=0, help_text='0-\u521b\u5efa\u672a\u53d1\u5e03, 1-\u53d1\u5e03\u672a\u9886\u53d6, 2-\u9886\u53d6\u672a\u5b8c\u6210, 3-\u5b8c\u6210\u4e14\u6210\u529f, 4-\u5b8c\u6210\u5374\u5931\u8d25, 5-\u53d6\u6d88', verbose_name='\u4efb\u52a1\u72b6\u6001')),
                ('instance', models.ForeignKey(blank=True, help_text='\u5f53\u6ca1\u6709\u865a\u62df\u673a\u53ef\u5173\u8054\u65f6\uff0c\u503c\u4e3aNone', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_instance', to='instance.Instance', verbose_name='\u4efb\u52a1\u7684\u5173\u8054\u865a\u62df\u673a')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_server', to='server.Server', verbose_name='\u4efb\u52a1\u7684\u5173\u8054\u8bbe\u5907')),
            ],
            options={
                'verbose_name': '\u6240\u6709\u4efb\u52a1\u6e05\u5355',
                'verbose_name_plural': '2-\u6240\u6709\u4efb\u52a1\u6e05\u5355',
            },
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u4efb\u52a1\u540d\u79f0')),
                ('type', models.IntegerField(default=0, help_text='\u8bf4\u660e: 1-\u65b0\u5efa\u865a\u62df\u673a;2-\u66f4\u65b0\u865a\u62df\u673a\u914d\u7f6e;3-\u5220\u9664\u865a\u62df\u673a;4-\u865a\u62df\u673a\u521b\u5efa\u5feb\u7167;5-\u865a\u62df\u673a\u6062\u590d\u5feb\u7167;7-\u5220\u9664\u5feb\u7167;8-\u7f51\u5361\u914d\u7f6e;20-\u542f\u52a8/\u505c\u6b62\u865a\u62df\u673a;40--\u4e0b\u8f7d\u4efb\u52a1;', verbose_name='\u4efb\u52a1\u7c7b\u578b\u53f7')),
                ('age', models.IntegerField(default=0, verbose_name='\u9886\u53d6\u6709\u6548\u671f(\u79d2)')),
                ('failed', models.IntegerField(default=0, help_text='\u63d0\u793a: 1\u5206\u949f: 60; 5\u5206\u949f: 300; 10\u5206\u949f: 600; \u534a\u5c0f\u65f6: 1800;', verbose_name='\u54cd\u5e94\u6709\u6548\u671f(\u79d2)')),
            ],
            options={
                'verbose_name': '\u4efb\u52a1\u6709\u6548\u671f',
                'verbose_name_plural': '1-\u4efb\u52a1\u7c7b\u578b\u6ce8\u518c',
            },
        ),
        migrations.AddField(
            model_name='tasklist',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_type', to='api.TaskType', verbose_name='\u4efb\u52a1\u7684\u5173\u8054\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='snapins',
            name='uuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='si_uuid', to='api.TaskList', verbose_name='\u4efb\u52a1\u7684\u5173\u8054UUID'),
        ),
        migrations.AddField(
            model_name='settingins',
            name='uuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='si2_uuid', to='api.TaskList', verbose_name='\u4efb\u52a1\u7684\u5173\u8054UUID'),
        ),
        migrations.AddField(
            model_name='setnetins',
            name='uuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sni_uuid', to='api.TaskList', verbose_name='\u4efb\u52a1\u7684\u5173\u8054UUID'),
        ),
        migrations.AddField(
            model_name='delins',
            name='uuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='di_uuid', to='api.TaskList', verbose_name='\u4efb\u52a1\u7684\u5173\u8054UUID'),
        ),
        migrations.AddField(
            model_name='ctrlins',
            name='uuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ci_uuid', to='api.TaskList', verbose_name='\u4efb\u52a1\u7684\u5173\u8054UUID'),
        ),
        migrations.AddField(
            model_name='addvmfile',
            name='uuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avf_uuid', to='api.TaskList', verbose_name='\u4efb\u52a1\u7684\u5173\u8054UUID'),
        ),
        migrations.AddField(
            model_name='addins',
            name='uuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_uuid', to='api.TaskList', verbose_name='\u4efb\u52a1\u7684\u5173\u8054UUID'),
        ),
        migrations.AddField(
            model_name='addins',
            name='vm_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_vmfiles', to='server.VmFile', verbose_name='\u5173\u8054VmFile'),
        ),
    ]
