# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160608_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='father_id',
            field=models.CharField(default=None, max_length=32, null=True, verbose_name='\u7236\u4efb\u52a1ID'),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='group_id',
            field=models.CharField(default=None, max_length=32, null=True, verbose_name='\u4efb\u52a1\u7ec4ID'),
        ),
    ]
