# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IosTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='VM\u6a21\u677f\u955c\u50cf\u540d\u79f0')),
                ('cpu_num', models.IntegerField(default=0, verbose_name='CPU(\u6838)')),
                ('cpu_model', models.IntegerField(default=1, help_text='\u6b64\u529f\u80fd\u6682\u65f6\u672a\u5b9e\u73b0\uff08\u914d\u65b9\uff09\uff0c\u5168\u90e8\u9ed8\u8ba4\u4e3a1', verbose_name='CPU\u6a21\u5f0f')),
                ('disk_model', models.IntegerField(default=1, help_text='\u6b64\u529f\u80fd\u6682\u65f6\u672a\u5b9e\u73b0\uff08\u914d\u65b9\uff09\uff0c\u5168\u90e8\u9ed8\u8ba4\u4e3a1', verbose_name='\u6570\u636e\u76d8\u6a21\u5f0f')),
                ('sys_disk_size', models.BigIntegerField(default=0, help_text='\u5355\u4f4d: Byte', verbose_name='\u7cfb\u7edf\u76d8\u5927\u5c0f')),
                ('data_disk_size', models.BigIntegerField(default=0, help_text='\u5355\u4f4d: Byte', verbose_name='\u6570\u636e\u76d8\u76d8\u5927\u5c0f')),
                ('mem_size', models.BigIntegerField(default=0, help_text='\u5355\u4f4d: Byte', verbose_name='\u5185\u5b58\u5927\u5c0f')),
                ('comment', models.TextField(verbose_name='\u5907\u6ce8\u4fe1\u606f')),
            ],
            options={
                'verbose_name': '\u8bbe\u5907\u955c\u50cf\u914d\u7f6e\u6a21\u677f\u8868',
                'verbose_name_plural': '3-\u8bbe\u5907\u955c\u50cf\u914d\u7f6e\u6a21\u677f\u8868',
            },
        ),
        migrations.CreateModel(
            name='SBasicStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(verbose_name='\u65f6\u95f4')),
                ('stat_type', models.CharField(help_text='\u9009\u9879\uff0ccpu_used, disk_used, mem_used', max_length=10, verbose_name='\u72b6\u6001\u7c7b\u578b')),
                ('value', models.FloatField(default=0, help_text='\u4fdd\u7559\u4e24\u4f4d\u5c0f\u6570', verbose_name='\u767e\u5206\u6bd4')),
            ],
            options={
                'verbose_name': '\u57fa\u7840\u72b6\u6001\u4fe1\u606f\u8868',
                'verbose_name_plural': '6-\u57fa\u7840\u72b6\u6001\u4fe1\u606f\u8868',
            },
        ),
        migrations.CreateModel(
            name='SDiskConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(help_text='\u8be5\u914d\u7f6e\u521b\u5efa\u7684\u65f6\u95f4', verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('refresh', models.DateTimeField(help_text='\u76ee\u7684\u662f\u786e\u5b9a\u8be5\u914d\u7f6e\u5931\u6548\u7684\u65f6\u95f4', verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('source', models.CharField(max_length=100, verbose_name='\u6e90\u6570\u636e\u76d8')),
                ('total_size', models.BigIntegerField(default=0, help_text='\u5355\u4f4d: Byte', verbose_name='\u603b\u5927\u5c0f')),
                ('mounted', models.CharField(max_length=100, verbose_name='\u6302\u8f7d\u8def\u5f84')),
            ],
            options={
                'verbose_name': '\u8bbe\u5907\u78c1\u76d8\u914d\u7f6e',
                'verbose_name_plural': '4-\u8bbe\u5907\u8bbe\u5907\u78c1\u76d8\u914d\u7f6e',
            },
        ),
        migrations.CreateModel(
            name='SDiskStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(help_text='\u6570\u503c\u548cDiskConf\u91ccrefresh\u4e00\u81f4', verbose_name='\u65f6\u95f4')),
                ('used', models.FloatField(default=0, help_text='\u4fdd\u7559\u4e24\u4f4d\u5c0f\u6570', verbose_name='\u4f7f\u7528\u7387')),
                ('util', models.FloatField(default=0, help_text='\u4fdd\u7559\u4e24\u4f4d\u5c0f\u6570', verbose_name='\u78c1\u76d8Util')),
                ('disk_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sds_disk', to='server.SDiskConf', verbose_name='\u5173\u8054\u7684\u78c1\u76d8\u914d\u7f6e')),
            ],
            options={
                'verbose_name': '\u78c1\u76d8\u72b6\u6001\u8be6\u60c5\u8868',
                'verbose_name_plural': '7-\u78c1\u76d8\u72b6\u6001\u8be6\u60c5\u8868',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='\u672a\u77e5', max_length=45, verbose_name='\u5355\u4f4d\u540d\u79f0')),
                ('alias', models.CharField(default='\u672a\u77e5', max_length=45, verbose_name='\u8bbe\u5907\u522b\u540d')),
                ('islock', models.IntegerField(default=1, help_text='0:\u9501\u5b9a\uff1b1:\u89e3\u9501', verbose_name='\u9501\u5b9a\u72b6\u6001')),
                ('architecture', models.CharField(default='\u672a\u77e5', max_length=10, verbose_name='\u7cfb\u7edf\u4f4d\u6570')),
                ('version', models.CharField(default='0.0.0', max_length=10, verbose_name='\u4e1a\u52a1\u5305\u7248\u672c')),
                ('libvirt_version', models.CharField(default='0.0.0', max_length=10, verbose_name='libvirt\u7248\u672c')),
                ('hv_version', models.CharField(default='0.0.0', max_length=10, verbose_name='hypervisor\u7248\u672c')),
                ('cpu_name', models.CharField(default='\u672a\u77e5', max_length=100, verbose_name='CPU\u540d\u79f0')),
                ('cpu_num', models.IntegerField(default=0, verbose_name='CPU(\u6838)')),
                ('mem_size', models.BigIntegerField(default=0, verbose_name='\u5185\u5b58\u603b\u6570(Byte)')),
                ('disk_size', models.BigIntegerField(default=0, verbose_name='\u78c1\u76d8\u5927\u5c0f(Byte)')),
                ('data_disk_num', models.IntegerField(default=0, verbose_name='\u6570\u636e\u76d8\u6570\u91cf(\u4e2a)')),
                ('sn', models.CharField(max_length=13, verbose_name='sn')),
                ('refresh', models.DateTimeField(help_text='\u7528\u4e8e\u5224\u65ad\u8bbe\u5907\u662f\u5426\u5931\u8054\uff0c\u6839\u636e\u8bbe\u5907\u7684host_status\u53cd\u9988\u6765\u66f4\u65b0', null=True, verbose_name='\u5237\u65b0\u65f6\u95f4')),
                ('ip', models.GenericIPAddressField(default='0.0.0.0', verbose_name='\u51fa\u53e3IP')),
                ('status', models.IntegerField(default=0, help_text='(1--\u5728\u7ebf; 0--\u5173\u673a;  2--\u524d\u7aef\u663e\u793a(\u5931\u8054),\u5237\u65b0\u65f6\u95f4\u8d85\u8fc7\u4e00\u5c0f\u65f6)', verbose_name='\u72b6\u6001')),
            ],
            options={
                'verbose_name': '\u8bbe\u5907\u6e05\u5355',
                'verbose_name_plural': '1-\u8bbe\u5907\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='SNetConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(help_text='\u8be5\u914d\u7f6e\u521b\u5efa\u7684\u65f6\u95f4', verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('refresh', models.DateTimeField(help_text='\u76ee\u7684\u662f\u786e\u5b9a\u8be5\u914d\u7f6e\u5931\u6548\u7684\u65f6\u95f4', verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('name', models.CharField(max_length=30, verbose_name='\u7f51\u5361\u540d\u79f0')),
                ('net_type', models.CharField(help_text='\u8bf4\u660e: monitor-\u955c\u50cf\u7f51\u5361\uff1b server-\u670d\u52a1\u7f51\u5361', max_length=20, verbose_name='\u7f51\u5361\u7c7b\u578b')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snc_server', to='server.Server', verbose_name='\u7f51\u5361\u914d\u7f6e\u7684\u5173\u8054\u8bbe\u5907')),
            ],
            options={
                'verbose_name': '\u8bbe\u5907\u7f51\u5361\u914d\u7f6e',
                'verbose_name_plural': '5-\u8bbe\u5907\u7f51\u5361\u914d\u7f6e',
            },
        ),
        migrations.CreateModel(
            name='SNetStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(help_text='\u6570\u503c\u548cDiskConf\u91ccrefresh\u4e00\u81f4', verbose_name='\u65f6\u95f4')),
                ('net_in', models.BigIntegerField(default=0, help_text='\u5355\u4f4d: KBps', verbose_name='\u5165\u53e3\u6d41\u91cf')),
                ('net_out', models.BigIntegerField(default=0, help_text='\u5355\u4f4d: KBps', verbose_name='\u51fa\u53e3\u6d41\u91cf')),
                ('net_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sns_net', to='server.SNetConf', verbose_name='\u5173\u8054\u7684\u7f51\u7edc\u914d\u7f6e')),
            ],
            options={
                'verbose_name': '\u7f51\u7edc\u72b6\u6001\u8be6\u60c5\u8868',
                'verbose_name_plural': '8-\u7f51\u7edc\u72b6\u6001\u8be6\u60c5\u8868',
            },
        ),
        migrations.CreateModel(
            name='VmFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='VM\u955c\u50cf\u540d\u79f0')),
                ('size', models.BigIntegerField(default=0, help_text='\u5355\u4f4d: byte', verbose_name='\u955c\u50cf\u5927\u5c0f')),
                ('format', models.IntegerField(help_text='\u8bf4\u660e: 0--iso\uff1b1--qcow2; 2--\u672a\u77e5;', verbose_name='\u955c\u50cf\u7c7b\u578b')),
                ('source', models.IntegerField(help_text='\u8bf4\u660e: 0--\u8bbe\u5907\u9884\u88c5 or FTP\u6dfb\u52a0\u5e76\u4e0b\u8f7d\u5b8c\u6210\uff1b 1--FTP\u6dfb\u52a0\u672a\u4e0b\u8f7d\uff1b 2--\u672a\u77e5;', verbose_name='\u955c\u50cf\u6587\u4ef6\u6765\u6e90')),
                ('path', models.CharField(help_text='\u4e00\u822c\u662f\u670d\u52a1\u7aef\u914d\u7f6e\u7684\u6a21\u677f\u8def\u5f84\u548c\u955c\u50cf\u8def\u5f84', max_length=50, verbose_name='\u955c\u50cf\u4fdd\u5b58\u8def\u7ecf')),
                ('comment', models.TextField(verbose_name='\u5907\u6ce8\u4fe1\u606f')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vf_server', to='server.Server', verbose_name='VM File\u7684\u5173\u8054\u8bbe\u5907')),
            ],
            options={
                'verbose_name': '\u8bbe\u5907VM Files\u8868',
                'verbose_name_plural': '2-\u8bbe\u5907VM Files\u8868',
            },
        ),
        migrations.AddField(
            model_name='sdiskconf',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdc_server', to='server.Server', verbose_name='\u78c1\u76d8\u914d\u7f6e\u7684\u5173\u8054\u8bbe\u5907'),
        ),
        migrations.AddField(
            model_name='sbasicstat',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sbs_server', to='server.Server', verbose_name='\u57fa\u7840\u72b6\u6001\u7684\u5173\u8054\u8bbe\u5907'),
        ),
        migrations.AddField(
            model_name='iostemplate',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='it_server', to='server.Server', verbose_name='\u955c\u50cf\u6a21\u677f\u7684\u5173\u8054\u8bbe\u5907'),
        ),
        migrations.AddField(
            model_name='iostemplate',
            name='vm_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vm_files', to='server.VmFile', verbose_name='\u5173\u8054VmFile'),
        ),
    ]
